# Generated by Django 5.2 on 2025-11-24 13:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, unique=True, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title', unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
