# Generated by Django 5.2 on 2025-11-24 17:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_slug_product_basket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=True,
                populate_from="title",
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
