# Generated by Django 5.2 on 2025-11-24 18:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                always_update=True,
                editable=False,
                populate_from="title",
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
