# Generated by Django 5.2 on 2025-11-24 19:17

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default="",
                editable=False,
                populate_from="title",
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
