# Generated by Django 5.2 on 2025-11-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="production_country",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="страна производитель"
            ),
        ),
    ]
