# Generated by Django 5.2 on 2025-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rules',
            field=models.BooleanField(default=False, verbose_name='согласен с правилами'),
        ),
    ]
