# Generated by Django 5.2 on 2025-11-24 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=150, validators=[django.core.validators.RegexValidator('^[А-Яа-яЁё\\s-]+$', message='Отчество может содержать только русские буквы, пробелы и дефисы')], verbose_name='отчество'),
        ),
    ]
